### ISSUE TITLE
Trying to keep in touch

### ISSUE THREAD

**Issue by fritzgeralds** [dueshane/mf-bs-finalproject#2]
Hey Dueshane,

We lost slack but are trying to keep in touch. Find me on LinkedIn so we can invite you to Discord.

**Comment by dueshane** [comment]
Definitely, been occupied with life but I will make a LinkedIn profile soonSent from my iPhoneOn Jun 4, 2023, at 2:49 PM, fritzgeralds ***@***.***> wrote:﻿
Hey Dueshane,
We lost slack but are trying to keep in touch. Find me on LinkedIn so we can invite you to Discord.
